% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by Neural Fitting app
% Created 03-Jan-2021 00:35:15
%
% This script assumes these variables are defined:
%
%   input - input data.
%   target - target data.

x = input';
t = target';

% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'trainlm';  % Levenberg-Marquardt backpropagation.

% Create a Fitting Network
hiddenLayerSize = 10;
net = fitnet(hiddenLayerSize,trainFcn);

% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;

% Train the Network
[net,tr] = train(net,x,t);

% Test the Network
y = net(x);
e = gsubtract(t,y);
performance = perform(net,t,y)

% View the Network
view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, ploterrhist(e)
%figure, plotregression(t,y)
%figure, plotfit(net,x,t)


% -----------------------------------------------------------------------
% Iris Dataseti üzerinde islemler yap?yoruz. 
% Dogrudan githubdan da indirilebilir veya default matlabdada yukludur.

% Öncelikli olarak verielri yukledik.
% Ard?ndan veriyi input/output seklinde ay?rd?k. 
% Bu islemden sonra nftool yazarak toola gittik. 
% Oradaki belli secimleri yaparak NN modeli olusturduk. 
% Cikan sonuclar? kaydettik. 

output=output';
%As?l degerler ile tahmin edilen degerleri yan yana yazd?ral?m. 
ciktilar = [target output];

%Corelasyonu hesaplatalim:
%Corelasyon degeri ne kadar 1'e yak?nsa sonuclar o kadar iyi gelmi?
%demektir. Corelasyon = [-1,1]. 
r=corr(target,output);
